spring:
  application:
    name: movie-info-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
  tomcat:
    max-threads: 100