spring:
  application:
    name: rating-data-service
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true

config: coming from local