spring:
  application:
    name: movie-catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

config: coming from local