spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vskrahul/spring-boot-cloud.git
          searchPaths: cloud-git-config/{application}
  config:
    name: application.yml
  application:
    name: spring cloud config server

server:
  port: 8888

